---
abstract: 'IRC frontend to NatTrivia'
author:
  - 'Nuno Carvalho <smash@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.59, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bot-BasicBot-Pluggable-Module-NatTrivia
no_index:
  directory:
    - t
    - inc
requires:
  Bot::BasicBot::Pluggable::Module: 0
  Test::More: 0
version: 0.01_2
